// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UTfVHNxBDxhqw0jp-Bn1I2tDsfAXLH0',
    appId: '1:1098970532641:web:9ac93c548d4d25aaf58c60',
    messagingSenderId: '1098970532641',
    projectId: 'voxify-d63e0',
    authDomain: 'voxify-d63e0.firebaseapp.com',
    storageBucket: 'voxify-d63e0.appspot.com',
    measurementId: 'G-SXW6SL3LYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-RfxzoeJxc5nrYzVXTMVuktzWGKCG4VE',
    appId: '1:1098970532641:android:bf25182b604d32f7f58c60',
    messagingSenderId: '1098970532641',
    projectId: 'voxify-d63e0',
    storageBucket: 'voxify-d63e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo9jqIqXnK7HaPplOkDRs3pI_MYRDuDbU',
    appId: '1:1098970532641:ios:37605d09f472a32cf58c60',
    messagingSenderId: '1098970532641',
    projectId: 'voxify-d63e0',
    storageBucket: 'voxify-d63e0.appspot.com',
    iosBundleId: 'com.example.voxify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo9jqIqXnK7HaPplOkDRs3pI_MYRDuDbU',
    appId: '1:1098970532641:ios:6dc7968940414233f58c60',
    messagingSenderId: '1098970532641',
    projectId: 'voxify-d63e0',
    storageBucket: 'voxify-d63e0.appspot.com',
    iosBundleId: 'com.example.voxify.RunnerTests',
  );
}
